import { NextRequest, NextResponse } from 'next/server';

import { SupabaseClient } from '@supabase/supabase-js';

import * as z from 'zod';

import { getLogger } from '@kit/shared/logger';
import { getSupabaseServerAdminClient } from '@kit/supabase/server-admin-client';
import { verifyInvitationToken } from '@kit/team-accounts/invitation-signature';

import pathsConfig from '~/config/paths.config';
import { Database } from '~/lib/database.types';

// invite tokens are v4 UUIDs (see add_invitations_to_account)
const InviteTokenSchema = z.string().uuid();

/**
 * @name GET
 * @description Entry point for team invitation email links.
 *
 * Flow:
 * 1. User clicks the email link: /join/accept?invite_token=xxx&sig=yyy
 * 2. If the signature is valid (i.e. the link was generated by the server and
 *    emailed to the invitee), generate a fresh Supabase auth link on-the-fly and
 *    sign the user in (one-click join, works for the full 7-day window).
 * 3. If the signature is missing or invalid (forged link, or an in-flight link
 *    issued before signing was introduced), DO NOT auto-authenticate. Forward to
 *    the secure /join page via sign-up/sign-in, where requireUser + the
 *    invitation.email === user.email check gate acceptance.
 *
 * SECURITY: the invite_token alone is NOT sufficient to mint a session, because
 * it is readable by members of the inviting account (RLS / data API). Only a
 * link carrying a valid `sig` — which a token-reader cannot forge — triggers the
 * one-click path. See @kit/team-accounts/invitation-signature.
 */
export async function GET(request: NextRequest) {
  const logger = await getLogger();
  const { searchParams } = new URL(request.url);
  const inviteToken = searchParams.get('invite_token');
  const signature = searchParams.get('sig');

  const ctx = {
    name: 'join.accept',
    inviteTokenFingerprint: getSecretFingerprint(inviteToken),
  };

  // Validate invite token is provided and well-formed (cheap input hygiene).
  if (!inviteToken || !InviteTokenSchema.safeParse(inviteToken).success) {
    logger.warn(ctx, 'Missing or malformed invite_token parameter');

    return redirectToError('Invalid invitation link');
  }

  // If the link is not validly signed, never auto-authenticate. Send the user
  // through the secure /join flow (sign-up/sign-in, then email-matched accept).
  if (!verifyInvitationToken(inviteToken, signature)) {
    logger.info(
      ctx,
      'Unsigned/invalid invitation link; routing through secure join flow',
    );

    return redirectToSecureJoin(inviteToken);
  }

  try {
    const adminClient = getSupabaseServerAdminClient();

    // Query invitation from database (admin client; RLS-bypassing)
    const { data: invitation, error: invitationError } = await adminClient
      .from('invitations')
      .select('id, email')
      .eq('invite_token', inviteToken)
      .gte('expires_at', new Date().toISOString())
      .single();

    // Handle invitation not found or expired
    if (invitationError || !invitation) {
      logger.warn(
        {
          ...ctx,
          error: invitationError,
        },
        'Invitation not found or expired',
      );

      return redirectToError('Invitation not found or expired');
    }

    logger.info(
      {
        ...ctx,
        invitationId: invitation.id,
      },
      'Valid signed invitation found. Generating auth link...',
    );

    // Determine email link type based on user existence
    // 'invite' for new users (creates account + authenticates)
    // 'magiclink' for existing users (authenticates only)
    const emailLinkType = await determineEmailLinkType(
      adminClient,
      invitation.email,
    );

    // Generate fresh Supabase auth link
    const generateLinkResponse = await adminClient.auth.admin.generateLink({
      email: invitation.email,
      type: emailLinkType,
    });

    if (generateLinkResponse.error) {
      logger.error(
        {
          ...ctx,
          error: generateLinkResponse.error,
        },
        'Failed to generate auth link',
      );

      throw generateLinkResponse.error;
    }

    // Extract token from generated link
    const verifyLink = generateLinkResponse.data.properties?.action_link;
    const token = new URL(verifyLink).searchParams.get('token');

    if (!token) {
      logger.error(ctx, 'Token not found in generated link');
      throw new Error('Token in verify link from Supabase Auth was not found');
    }

    // Build redirect URL to auth confirmation with fresh token
    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;
    const authCallbackUrl = new URL('/auth/confirm', siteUrl);

    // Add auth parameters
    authCallbackUrl.searchParams.set('token_hash', token);
    authCallbackUrl.searchParams.set('type', emailLinkType);

    // Add next parameter to redirect to join page after auth
    const joinUrl = new URL(pathsConfig.app.joinTeam, siteUrl);
    joinUrl.searchParams.set('invite_token', inviteToken);

    // Mark if this is a new user so /join page can redirect to /identities
    if (emailLinkType === 'invite') {
      joinUrl.searchParams.set('is_new_user', 'true');
    }

    // Use pathname + search to create a safe relative path for validation
    authCallbackUrl.searchParams.set('next', joinUrl.pathname + joinUrl.search);

    logger.info(
      {
        ...ctx,
        redirectUrl: authCallbackUrl.pathname,
      },
      'Redirecting to auth confirmation with fresh token',
    );

    // Redirect to auth confirmation
    return NextResponse.redirect(authCallbackUrl);
  } catch (error) {
    logger.error(
      {
        ...ctx,
        error,
      },
      'Failed to process invitation acceptance',
    );

    return redirectToError('An error occurred processing your invitation');
  }
}

/**
 * @name determineEmailLinkType
 * @description Determines whether to use 'invite' or 'magiclink' based on user existence
 */
async function determineEmailLinkType(
  adminClient: SupabaseClient<Database>,
  email: string,
): Promise<'invite' | 'magiclink'> {
  const user = await adminClient
    .from('accounts')
    .select('id')
    .eq('email', email)
    .single();

  // If user not found, return 'invite' type (allows registration)
  if (user.error || !user.data) {
    return 'invite';
  }

  // If user exists, return 'magiclink' type (sign in)
  return 'magiclink';
}

/**
 * @name redirectToSecureJoin
 * @description Forwards to the secure /join page via sign-up, preserving the
 * invite token in the `next` param (which round-trips through the auth flow).
 * No session is minted from the token on this path.
 */
function redirectToSecureJoin(inviteToken: string): NextResponse {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;

  const joinUrl = new URL(pathsConfig.app.joinTeam, siteUrl);
  joinUrl.searchParams.set('invite_token', inviteToken);

  const signUpUrl = new URL(pathsConfig.auth.signUp, siteUrl);
  signUpUrl.searchParams.set('next', joinUrl.pathname + joinUrl.search);

  return NextResponse.redirect(signUpUrl);
}

/**
 * @name redirectToError
 * @description Redirects to join page with error message
 */
function redirectToError(message: string): NextResponse {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;
  const errorUrl = new URL(pathsConfig.app.joinTeam, siteUrl);

  errorUrl.searchParams.set('error', message);

  return NextResponse.redirect(errorUrl);
}

function getSecretFingerprint(value: string | null) {
  if (!value) {
    return null;
  }

  if (value.length <= 8) {
    return '[redacted]';
  }

  return `${value.slice(0, 4)}...${value.slice(-4)}`;
}
